databases:
  - name: personalsite
    databaseName: personalsite
    user: personalsite

services:
  - type: web
    name: personalsite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn personalsite.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personalsite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4